apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database/postgres-configmap.yaml
  - database/postgres-storage.yaml
  - database/postgres-deployment.yaml
  - database/postgres-svc.yaml
  - webapp/backend-svc.yaml
  - webapp/backend-deployment.yaml
  - webapp/frontend-svc.yaml
  - webapp/frontend-deployment.yaml