apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: LoadBalancer
