apiVersion: v2
name: backend
description: A Helm chart for Backend App
type: application
version: 0.1.0
appVersion: "1.16.0"
keywords:
  - "javascript"
  - "app"
home: https://github.com/evertonlperes/k8s-deployment-sample/tree/main/helm/backend
maintainers:
  - name: Everton Peres
    url: https://github.com/evertonlperes
