app:
  name: app
  group: app
  replicaCount: 1
  container:
    image: frontend-molina
    port: 3001
    config: []
    env:
       - key: key
         value: value
  service:
    type: ClusterIP
    port: 3001